colrev\_core.exceptions.DirtyRepoAfterProcessingError
=====================================================

.. currentmodule:: colrev_core.exceptions

.. autoexception:: DirtyRepoAfterProcessingError
